### ISSUE TITLE
A compilation error using Xcode 16

### ISSUE THREAD

**Issue by MaximLitvinyuk** [queueit/ios-webui-sdk#35] opened 2024-09-16 13:44 UTC
Projects using Xcode 16 and the latest ios-webui-sdk release (3.4.2) will not compile because of the next error: 

`/Users/max/Library/Developer/Xcode/DerivedData/ios-webui-sdk-example-apxgnkmypgwhrjemxlegjwpayugr/SourcePackages/checkouts/ios-webui-sdk/QueueItLib/QueueService_NSURLConnectionRequest.h:19:1 'QueueService_NSURLConnectionRequestDelegate' has different definitions in different modules; first difference is definition in module 'QueueITLibrary' found method 'requestDidComplete:' with 1st parameter of type 'QueueService_NSURLConnectionRequest *__strong'
` 

The example project where it can be reproduced can be found here: 
https://github.com/MaximLitvinyuk/ios-webui-sdk-example-xcode-16-error

NOTE: in order to reproduce it, you should run the project using Xcode 16

**Comment by 3520kramer** [comment] 2024-09-18 09:38
@MaximLitvinyuk Thanks for providing us with this information and including a project to reproduce in. Do you have a workaround or is this a complete blocker for you?

**Comment by sbo-nemlig** [comment] 2024-09-19 06:27
I can see that @MaximLitvinyuk  has also submitted a PR for the fix https://github.com/queueit/ios-webui-sdk/pull/36

**Comment by 3520kramer** [comment] 2024-09-19 06:40
Yes thanks, we are aware of the PR. What i would like to know is if @MaximLitvinyuk can use the workaround without us releasing a new version or if it's a complete blocker? And i would like to know if this is the case for you @sbo-nemlig as well?

**Comment by sbo-nemlig** [comment] 2024-09-19 06:43
Yes, this issue is preventing us from using Xcode 16 and iOS 18. I'm not sure if there's a workaround other than using @MaximLitvinyuk's fork, as the problem seems to be related to naming conventions within your SDK.

**Comment by 3520kramer** [comment] 2024-09-19 06:45
Would you be able to use that until we have released a fix for this issue? ETA is beginning of next week

**Comment by sbo-nemlig** [comment] 2024-09-19 06:47
Yes, we can also wait a week if that is the ETA

**Comment by 3520kramer** [comment] 2024-09-19 08:34
That's great! Thank you for the patience

**Comment by MaximLitvinyuk** [comment] 2024-09-19 09:44
Hi, thanks for contacting me, I think we could wait for a week as well

**Comment by MaximLitvinyuk** [comment] 2024-09-25 12:39
Hi guys! Do you have any updates about the new version?

**Comment by 3520kramer** [comment] 2024-09-27 13:57
We have released version 3.4.3 which should solve the issue. Please open a new issue if the error persists

**Closed by 3520kramer** 2024-09-27 13:57 UTC
