### ISSUE TITLE
iOS 13 Fullscreen not dismissible

### ISSUE THREAD

**Issue by andrewescutia** [queueit/ios-webui-sdk#18] opened 2022-01-07 18:36 UTC
It appears that with the change below that the queuing modal is no longer dismissible? 
` if (@available(iOS 13.0, *)) {
            [queueWKVC setModalPresentationStyle: UIModalPresentationFullScreen];
        }`

Testing on iOS 15

Queue It Versions
 - 2.12.2 is dismissible
 - 3.0.9 not dismissible

was that intended?

**Comment by frwiqueueit** [comment] 2022-01-10 07:20
Thank you for bringing this to our attention. 
We will look into it at get back to you.

**Comment by sp0x** [comment] 2022-01-14 12:28
This change was introduced in 2.12.3.
The idea was that the waiting room should be displayed in full screen.
This change was intended. If you need a way to exit the waiting room there is a special link that can be added to the design.
Can you share more about your use case?

**Comment by andrewescutia** [comment] 2022-01-14 16:07
I dont believe we have any issues if that is the intent. I'll note it and mention the use of an exit link. 

Thanks.

**Comment by frwiqueueit** [comment] 2022-01-17 08:19
OK, I will close this issue

**Closed by frwiqueueit** 2022-01-17 08:19 UTC
